### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by kchu93** [kevinchu676/visual-movement#2]
- [x] New Account Creation
- [x] Login
- [x] Guest/Demo Login
- [x] Styling
- [x] Nav Bar

**Comment by evhumphrey** [comment]
- [x] Add hover effects to Sign up, Sign In links in nav bar 
- [x] Add hover effects to Logout button
- [x] Hover effect for demo button should make it either darker or lighter (not the same color as other buttons, it's a bit confusing)

Other than that, looks good (I would spend at most 15 minutes on this when you get a chance

**Comment by evhumphrey** [comment]
👍
